# Generated by Django 4.2 on 2023-04-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='port',
            field=models.IntegerField(),
        ),
    ]
