# Generated by Django 4.2 on 2023-04-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0002_alter_robot_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
